"""add_exercise_configurations_and_sets

Revision ID: 273789964714
Revises: b61961abf6a5
Create Date: 2026-08-11 17:34:30.174974

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "273789964714"
down_revision: Union[str, Sequence[str], None] = "b61961abf6a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ruff: noqa: E501
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise_configurations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("training_day_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(), nullable=False),
        sa.Column("rest_after_exercise_seconds", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(["training_day_id"], ["training_days.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "training_day_id", "exercise_id", name="uq_exercise_config_training_day_exercise"
        ),
        sa.UniqueConstraint(
            "training_day_id", "position", name="uq_exercise_config_training_day_position"
        ),
    )
    op.create_table(
        "configured_sets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("exercise_configuration_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("target_value", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("target_weight_kg", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("target_rir", sa.Integer(), nullable=True),
        sa.Column("eccentric_seconds", sa.Integer(), nullable=True),
        sa.Column("stretched_pause_seconds", sa.Integer(), nullable=True),
        sa.Column("concentric_seconds", sa.Integer(), nullable=True),
        sa.Column("peak_contraction_seconds", sa.Integer(), nullable=True),
        sa.Column("rest_after_set_seconds", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_configuration_id"], ["exercise_configurations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "exercise_configuration_id", "position", name="uq_configured_set_config_position"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("configured_sets")
    op.drop_table("exercise_configurations")
    # ### end Alembic commands ###
