"""add_workout_tables

Revision ID: 5f6392b90798
Revises: f11a1b2c3d4e
Create Date: 2026-08-12 10:23:38.388381

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f6392b90798"
down_revision: Union[str, Sequence[str], None] = "f11a1b2c3d4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workout_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("source_routine_id", sa.Integer(), nullable=True),
        sa.Column("source_training_day_id", sa.Integer(), nullable=True),
        sa.Column("routine_name", sa.String(length=120), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("scheduled_week_position", sa.Integer(), nullable=False),
        sa.Column("scheduled_slot_was_rest", sa.Integer(), nullable=False),
        sa.Column("scheduled_training_day_id", sa.Integer(), nullable=True),
        sa.Column("scheduled_training_day_name", sa.String(length=120), nullable=True),
        sa.Column("selected_training_day_id", sa.Integer(), nullable=False),
        sa.Column("selected_training_day_name", sa.String(length=120), nullable=False),
        sa.Column("selected_week_position", sa.Integer(), nullable=False),
        sa.Column("selection_kind", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "selection_kind IN ('scheduled', 'alternate')",
            name="ck_workout_sessions_selection_kind",
        ),
        sa.CheckConstraint(
            "scheduled_slot_was_rest IN (0, 1)", name="ck_workout_sessions_scheduled_slot_was_rest"
        ),
        sa.CheckConstraint(
            "status IN ('in_progress', 'cancelled')", name="ck_workout_sessions_status"
        ),
        sa.CheckConstraint(
            "(status = 'in_progress' AND cancelled_at IS NULL) OR "
            "(status = 'cancelled' AND cancelled_at IS NOT NULL)",
            name="ck_workout_sessions_status_timestamp",
        ),
        sa.CheckConstraint(
            "(scheduled_slot_was_rest = 1 AND scheduled_training_day_id IS NULL "
            "AND scheduled_training_day_name IS NULL AND selection_kind = 'alternate') OR "
            "(scheduled_slot_was_rest = 0 AND scheduled_training_day_id IS NOT NULL "
            "AND scheduled_training_day_name IS NOT NULL)",
            name="ck_workout_sessions_scheduled_slot",
        ),
        sa.CheckConstraint(
            "selection_kind = 'alternate' OR selected_training_day_id = scheduled_training_day_id",
            name="ck_workout_sessions_scheduled_selection",
        ),
        sa.CheckConstraint(
            "scheduled_week_position >= 1 AND scheduled_week_position <= 7",
            name="ck_workout_sessions_scheduled_week_position",
        ),
        sa.CheckConstraint(
            "selected_week_position >= 1 AND selected_week_position <= 7",
            name="ck_workout_sessions_selected_week_position",
        ),
        sa.ForeignKeyConstraint(["source_routine_id"], ["routines.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_training_day_id"], ["training_days.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "user_id", name="uq_workout_session_id_user_id"),
    )
    op.create_table(
        "active_workouts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workout_session_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workout_session_id", "user_id"],
            ["workout_sessions.id", "workout_sessions.user_id"],
            name="fk_active_workout_session_user",
        ),
        sa.ForeignKeyConstraint(
            ["workout_session_id"], ["workout_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        sa.UniqueConstraint("workout_session_id"),
    )
    op.create_table(
        "workout_exercises",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workout_session_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("source_exercise_id", sa.Integer(), nullable=True),
        sa.Column("exercise_slug", sa.String(length=100), nullable=False),
        sa.Column("exercise_name", sa.String(length=120), nullable=False),
        sa.Column("target_type", sa.String(), nullable=False),
        sa.Column("rest_after_exercise_seconds", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.CheckConstraint(
            "target_type IN ('repetitions', 'duration_seconds', 'distance_meters')",
            name="ck_workout_exercises_target_type",
        ),
        sa.CheckConstraint("position >= 1", name="ck_workout_exercises_position"),
        sa.ForeignKeyConstraint(["source_exercise_id"], ["exercises.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["workout_session_id"], ["workout_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workout_session_id", "position", name="uq_workout_exercise_session_position"
        ),
    )
    op.create_table(
        "workout_planned_sets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workout_exercise_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("target_value", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("target_weight_kg", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("target_rir", sa.Integer(), nullable=True),
        sa.Column("eccentric_seconds", sa.Integer(), nullable=True),
        sa.Column("stretched_pause_seconds", sa.Integer(), nullable=True),
        sa.Column("concentric_seconds", sa.Integer(), nullable=True),
        sa.Column("peak_contraction_seconds", sa.Integer(), nullable=True),
        sa.Column("rest_after_set_seconds", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.CheckConstraint("position >= 1", name="ck_workout_planned_sets_position"),
        sa.ForeignKeyConstraint(
            ["workout_exercise_id"], ["workout_exercises.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workout_exercise_id", "position", name="uq_workout_planned_set_exercise_position"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workout_planned_sets")
    op.drop_table("workout_exercises")
    op.drop_table("active_workouts")
    op.drop_table("workout_sessions")
    # ### end Alembic commands ###
