"""Canonical seed data for the FlexGym exercise catalog.

Each tuple is (slug, name, primary_muscle, secondary_muscles, equipment,
movement_pattern, execution_type, instructions).
"""

# ruff: noqa: E501

EXERCISE_SEED_DATA: list[tuple[str, str, str, list[str], str, str, str, str]] = [
    # Chest
    (
        "barbell-bench-press",
        "Barbell Bench Press",
        "chest",
        ["triceps", "shoulders"],
        "barbell",
        "horizontal_push",
        "bilateral",
        "Lie on a flat bench with the bar over the chest. Lower it under control, then press until the arms are extended.",
    ),
    (
        "incline-barbell-bench-press",
        "Incline Barbell Bench Press",
        "chest",
        ["shoulders", "triceps"],
        "barbell",
        "horizontal_push",
        "bilateral",
        "Lie on an inclined bench with the bar above the upper chest. Lower it under control and press back up.",
    ),
    (
        "dumbbell-bench-press",
        "Dumbbell Bench Press",
        "chest",
        ["triceps", "shoulders"],
        "dumbbell",
        "horizontal_push",
        "bilateral",
        "Lie on a flat bench with a dumbbell beside each side of the chest. Press them upward and lower them under control.",
    ),
    (
        "incline-dumbbell-bench-press",
        "Incline Dumbbell Bench Press",
        "chest",
        ["shoulders", "triceps"],
        "dumbbell",
        "horizontal_push",
        "bilateral",
        "Lie on an inclined bench holding the dumbbells near the upper chest. Press upward and return under control.",
    ),
    (
        "machine-chest-press",
        "Machine Chest Press",
        "chest",
        ["triceps", "shoulders"],
        "machine",
        "horizontal_push",
        "bilateral",
        "Adjust the seat so the handles align near the chest. Press forward, then return without letting the weight stack slam.",
    ),
    (
        "cable-chest-fly",
        "Cable Chest Fly",
        "chest",
        ["shoulders"],
        "cable",
        "horizontal_adduction",
        "bilateral",
        "Stand between the cables with the arms open and slightly bent. Bring the hands together in front of the chest, then reopen under control.",
    ),
    (
        "push-up",
        "Push-Up",
        "chest",
        ["triceps", "shoulders", "core"],
        "bodyweight",
        "horizontal_push",
        "bilateral",
        "Start in a straight-body plank with hands below or slightly outside the shoulders. Lower the chest toward the floor and push back up.",
    ),
    (
        "parallel-bar-dip",
        "Parallel Bar Dip",
        "chest",
        ["triceps", "shoulders"],
        "bodyweight",
        "vertical_push",
        "bilateral",
        "Support the body on parallel bars and lower by bending the elbows. Press back to the supported position within a controlled range.",
    ),
    # Back
    (
        "pull-up",
        "Pull-Up",
        "lats",
        ["biceps", "upper_back", "core"],
        "pull_up_bar",
        "vertical_pull",
        "bilateral",
        "Hang from a bar with an overhand grip. Pull until the upper chest approaches the bar, then lower under control.",
    ),
    (
        "chin-up",
        "Chin-Up",
        "lats",
        ["biceps", "upper_back", "core"],
        "pull_up_bar",
        "vertical_pull",
        "bilateral",
        "Hang from a bar with an underhand grip. Pull the body upward, then return to a controlled hang.",
    ),
    (
        "assisted-pull-up",
        "Assisted Pull-Up",
        "lats",
        ["biceps", "upper_back"],
        "machine",
        "vertical_pull",
        "bilateral",
        "Set the assistance and begin from a supported hang. Pull upward and lower under control while keeping the torso stable.",
    ),
    (
        "lat-pulldown",
        "Lat Pulldown",
        "lats",
        ["biceps", "upper_back"],
        "cable",
        "vertical_pull",
        "bilateral",
        "Sit with the thighs secured and grip the bar overhead. Pull it toward the upper chest, then let the arms extend under control.",
    ),
    (
        "straight-arm-cable-pulldown",
        "Straight-Arm Cable Pulldown",
        "lats",
        ["core"],
        "cable",
        "vertical_pull",
        "bilateral",
        "Stand facing a high cable with arms nearly straight. Draw the handle down toward the thighs, then return without turning it into an elbow pull.",
    ),
    (
        "barbell-bent-over-row",
        "Barbell Bent-Over Row",
        "upper_back",
        ["lats", "biceps", "hamstrings", "core"],
        "barbell",
        "horizontal_pull",
        "bilateral",
        "Hinge forward holding the bar below the shoulders. Row it toward the torso and lower it while maintaining the hinged position.",
    ),
    (
        "one-arm-dumbbell-row",
        "One-Arm Dumbbell Row",
        "lats",
        ["upper_back", "biceps"],
        "dumbbell",
        "horizontal_pull",
        "unilateral",
        "Support the torso and hold a dumbbell with one arm extended. Row it toward the hip, then lower under control.",
    ),
    (
        "seated-cable-row",
        "Seated Cable Row",
        "upper_back",
        ["lats", "biceps"],
        "cable",
        "horizontal_pull",
        "bilateral",
        "Sit tall with the cable in front and arms extended. Pull the handle toward the torso and return without rocking.",
    ),
    (
        "chest-supported-machine-row",
        "Chest-Supported Machine Row",
        "upper_back",
        ["lats", "biceps"],
        "machine",
        "horizontal_pull",
        "bilateral",
        "Set the chest against the pad and begin with arms extended. Pull the handles back, then return under control.",
    ),
    (
        "inverted-row",
        "Inverted Row",
        "upper_back",
        ["lats", "biceps", "core"],
        "bodyweight",
        "horizontal_pull",
        "bilateral",
        "Hang beneath a secure horizontal bar with the body straight. Pull the chest toward the bar and lower as one controlled unit.",
    ),
    (
        "resistance-band-row",
        "Resistance Band Row",
        "upper_back",
        ["lats", "biceps"],
        "resistance_band",
        "horizontal_pull",
        "bilateral",
        "Anchor the band in front and begin with arms extended. Pull the hands toward the torso, then return with steady tension.",
    ),
    # Shoulders
    (
        "barbell-overhead-press",
        "Barbell Overhead Press",
        "shoulders",
        ["triceps", "core"],
        "barbell",
        "vertical_push",
        "bilateral",
        "Hold the bar near the upper chest while standing. Press it overhead and lower it back under control.",
    ),
    (
        "dumbbell-shoulder-press",
        "Dumbbell Shoulder Press",
        "shoulders",
        ["triceps"],
        "dumbbell",
        "vertical_push",
        "bilateral",
        "Hold the dumbbells beside the shoulders while seated or standing. Press overhead and lower under control.",
    ),
    (
        "machine-shoulder-press",
        "Machine Shoulder Press",
        "shoulders",
        ["triceps"],
        "machine",
        "vertical_push",
        "bilateral",
        "Adjust the seat so the handles begin near shoulder height. Press upward and return under control.",
    ),
    (
        "dumbbell-lateral-raise",
        "Dumbbell Lateral Raise",
        "shoulders",
        [],
        "dumbbell",
        "shoulder_abduction",
        "bilateral",
        "Stand with dumbbells by the sides and elbows slightly bent. Raise the arms out to the sides, then lower under control.",
    ),
    (
        "cable-lateral-raise",
        "Cable Lateral Raise",
        "shoulders",
        [],
        "cable",
        "shoulder_abduction",
        "unilateral",
        "Stand beside a low cable and hold it with the outside hand. Raise the arm to the side, then return under control.",
    ),
    (
        "resistance-band-lateral-raise",
        "Resistance Band Lateral Raise",
        "shoulders",
        [],
        "resistance_band",
        "shoulder_abduction",
        "bilateral",
        "Stand on the band with the hands by the sides. Raise the arms outward against the band and lower steadily.",
    ),
    (
        "reverse-pec-deck",
        "Reverse Pec Deck",
        "shoulders",
        ["upper_back"],
        "machine",
        "horizontal_pull",
        "bilateral",
        "Sit facing the pad with the arms in front. Open the arms outward, then return the handles under control.",
    ),
    (
        "dumbbell-rear-delt-fly",
        "Dumbbell Rear Delt Fly",
        "shoulders",
        ["upper_back"],
        "dumbbell",
        "horizontal_pull",
        "bilateral",
        "Hinge forward with the dumbbells below the shoulders. Open the arms outward with soft elbows, then lower under control.",
    ),
    (
        "face-pull",
        "Face Pull",
        "shoulders",
        ["upper_back"],
        "cable",
        "horizontal_pull",
        "bilateral",
        "Set a rope near face height and begin with arms extended. Pull toward the face while separating the rope ends, then return slowly.",
    ),
    # Arms - Biceps
    (
        "barbell-curl",
        "Barbell Curl",
        "biceps",
        ["forearms"],
        "barbell",
        "elbow_flexion",
        "bilateral",
        "Stand with the bar at arm's length. Bend the elbows to raise it toward the shoulders, then lower without swinging the torso.",
    ),
    (
        "dumbbell-curl",
        "Dumbbell Curl",
        "biceps",
        ["forearms"],
        "dumbbell",
        "elbow_flexion",
        "bilateral",
        "Hold the dumbbells by the sides with arms extended. Curl them toward the shoulders and lower under control.",
    ),
    (
        "hammer-curl",
        "Hammer Curl",
        "biceps",
        ["forearms"],
        "dumbbell",
        "elbow_flexion",
        "bilateral",
        "Hold the dumbbells with palms facing inward. Bend the elbows to raise them, then lower while keeping the neutral grip.",
    ),
    (
        "cable-curl",
        "Cable Curl",
        "biceps",
        ["forearms"],
        "cable",
        "elbow_flexion",
        "bilateral",
        "Stand facing a low cable with arms extended. Curl the handle toward the shoulders and return with controlled tension.",
    ),
    (
        "resistance-band-curl",
        "Resistance Band Curl",
        "biceps",
        ["forearms"],
        "resistance_band",
        "elbow_flexion",
        "bilateral",
        "Stand on the band with arms extended. Curl the hands toward the shoulders, then lower steadily.",
    ),
    # Arms - Triceps
    (
        "cable-triceps-pushdown",
        "Cable Triceps Pushdown",
        "triceps",
        [],
        "cable",
        "elbow_extension",
        "bilateral",
        "Stand facing a high cable with elbows near the sides. Extend the elbows to move the handle down, then return under control.",
    ),
    (
        "overhead-cable-triceps-extension",
        "Overhead Cable Triceps Extension",
        "triceps",
        [],
        "cable",
        "elbow_extension",
        "bilateral",
        "Face away from a cable with the handle behind the head. Extend the elbows overhead, then return without changing the upper-arm position excessively.",
    ),
    (
        "dumbbell-overhead-triceps-extension",
        "Dumbbell Overhead Triceps Extension",
        "triceps",
        [],
        "dumbbell",
        "elbow_extension",
        "bilateral",
        "Hold one dumbbell overhead with both hands. Bend the elbows to lower it behind the head, then extend the arms.",
    ),
    (
        "close-grip-bench-press",
        "Close-Grip Bench Press",
        "triceps",
        ["chest", "shoulders"],
        "barbell",
        "horizontal_push",
        "bilateral",
        "Lie on a flat bench holding the bar with a moderately close grip. Lower it toward the chest and press up while keeping the elbows controlled.",
    ),
    (
        "resistance-band-triceps-extension",
        "Resistance Band Triceps Extension",
        "triceps",
        [],
        "resistance_band",
        "elbow_extension",
        "bilateral",
        "Anchor the band above or behind the body with elbows bent. Extend the elbows against the band and return steadily.",
    ),
    # Quadriceps and lunge patterns
    (
        "barbell-back-squat",
        "Barbell Back Squat",
        "quadriceps",
        ["glutes", "hamstrings", "core"],
        "barbell",
        "squat",
        "bilateral",
        "Support the bar across the upper back and stand with a stable stance. Squat down under control, then stand back up.",
    ),
    (
        "barbell-front-squat",
        "Barbell Front Squat",
        "quadriceps",
        ["glutes", "core"],
        "barbell",
        "squat",
        "bilateral",
        "Support the bar across the front of the shoulders. Squat while keeping the torso controlled, then stand back up.",
    ),
    (
        "goblet-squat",
        "Goblet Squat",
        "quadriceps",
        ["glutes", "core"],
        "dumbbell",
        "squat",
        "bilateral",
        "Hold a dumbbell close to the chest. Squat between the hips, then push through the feet to stand.",
    ),
    (
        "bodyweight-squat",
        "Bodyweight Squat",
        "quadriceps",
        ["glutes", "core"],
        "bodyweight",
        "squat",
        "bilateral",
        "Stand with a comfortable stance and arms free for balance. Sit down into a squat, then stand while keeping the feet planted.",
    ),
    (
        "leg-press",
        "Leg Press",
        "quadriceps",
        ["glutes", "hamstrings"],
        "machine",
        "squat",
        "bilateral",
        "Place the feet securely on the platform and release the safeties. Bend the knees to lower the platform, then press it away without locking out forcefully.",
    ),
    (
        "hack-squat",
        "Hack Squat",
        "quadriceps",
        ["glutes", "hamstrings"],
        "machine",
        "squat",
        "bilateral",
        "Set the shoulders and back against the machine pads. Lower by bending the knees and hips, then press back to standing.",
    ),
    (
        "bulgarian-split-squat",
        "Bulgarian Split Squat",
        "quadriceps",
        ["glutes", "hamstrings", "core"],
        "dumbbell",
        "lunge",
        "unilateral",
        "Place the rear foot on a bench and keep the front foot stable. Lower through the front leg, then stand back up before changing sides.",
    ),
    (
        "reverse-lunge",
        "Reverse Lunge",
        "quadriceps",
        ["glutes", "hamstrings", "core"],
        "bodyweight",
        "lunge",
        "alternating",
        "Step one foot backward and lower both knees under control. Push through the front foot to return and alternate sides.",
    ),
    (
        "walking-lunge",
        "Walking Lunge",
        "quadriceps",
        ["glutes", "hamstrings", "core"],
        "dumbbell",
        "lunge",
        "alternating",
        "Step forward into a lunge while holding the dumbbells by the sides. Rise and continue into the next step with the other leg.",
    ),
    (
        "leg-extension",
        "Leg Extension",
        "quadriceps",
        [],
        "machine",
        "knee_extension",
        "bilateral",
        "Adjust the machine so the knee aligns with its pivot. Extend the knees to raise the pad, then lower under control.",
    ),
    # Hamstrings, glutes, and hips
    (
        "conventional-deadlift",
        "Conventional Deadlift",
        "glutes",
        ["hamstrings", "quadriceps", "upper_back", "forearms", "core"],
        "barbell",
        "hinge",
        "bilateral",
        "Stand with the bar over the midfoot and grip it from a hinged position. Push the floor away to stand with the bar, then return it under control.",
    ),
    (
        "barbell-romanian-deadlift",
        "Barbell Romanian Deadlift",
        "hamstrings",
        ["glutes", "upper_back", "forearms", "core"],
        "barbell",
        "hinge",
        "bilateral",
        "Hold the bar in front of the thighs with soft knees. Hinge the hips back until the hamstrings are loaded, then stand tall.",
    ),
    (
        "dumbbell-romanian-deadlift",
        "Dumbbell Romanian Deadlift",
        "hamstrings",
        ["glutes", "forearms", "core"],
        "dumbbell",
        "hinge",
        "bilateral",
        "Hold the dumbbells in front of the thighs with soft knees. Hinge the hips back, then drive the hips forward to stand.",
    ),
    (
        "seated-leg-curl",
        "Seated Leg Curl",
        "hamstrings",
        [],
        "machine",
        "knee_flexion",
        "bilateral",
        "Adjust the machine so the knee aligns with its pivot and secure the pads. Bend the knees to pull the pad down, then return slowly.",
    ),
    (
        "lying-leg-curl",
        "Lying Leg Curl",
        "hamstrings",
        [],
        "machine",
        "knee_flexion",
        "bilateral",
        "Lie on the machine with the pad above the heels. Bend the knees to curl the pad upward, then lower under control.",
    ),
    (
        "barbell-hip-thrust",
        "Barbell Hip Thrust",
        "glutes",
        ["hamstrings", "core"],
        "barbell",
        "hip_thrust",
        "bilateral",
        "Place the upper back against a bench with the bar across the hips. Drive the hips upward, then lower under control.",
    ),
    (
        "glute-bridge",
        "Glute Bridge",
        "glutes",
        ["hamstrings", "core"],
        "bodyweight",
        "hip_thrust",
        "bilateral",
        "Lie on the back with knees bent and feet planted. Lift the hips until the torso and thighs align, then lower steadily.",
    ),
    (
        "single-leg-glute-bridge",
        "Single-Leg Glute Bridge",
        "glutes",
        ["hamstrings", "core"],
        "bodyweight",
        "hip_thrust",
        "unilateral",
        "Lie on the back with one foot planted and the other leg raised. Lift the hips using the planted leg, then lower before changing sides.",
    ),
    (
        "cable-pull-through",
        "Cable Pull-Through",
        "glutes",
        ["hamstrings", "core"],
        "cable",
        "hinge",
        "bilateral",
        "Face away from a low cable with the handle between the legs. Hinge back, then extend the hips to stand without pulling with the arms.",
    ),
    (
        "back-extension",
        "Back Extension",
        "glutes",
        ["hamstrings", "upper_back"],
        "machine",
        "hinge",
        "bilateral",
        "Set the pad below the hips and begin with the torso aligned. Hinge forward under control, then extend the hips to return to alignment.",
    ),
    (
        "machine-hip-abduction",
        "Machine Hip Abduction",
        "glutes",
        [],
        "machine",
        "hip_abduction",
        "bilateral",
        "Sit with the outer legs against the pads. Move the knees apart, then return under control.",
    ),
    (
        "cable-hip-abduction",
        "Cable Hip Abduction",
        "glutes",
        ["core"],
        "cable",
        "hip_abduction",
        "unilateral",
        "Attach a low cable to one ankle and stand side-on with support. Move the working leg outward, then return before changing sides.",
    ),
    (
        "machine-hip-adduction",
        "Machine Hip Adduction",
        "adductors",
        [],
        "machine",
        "hip_adduction",
        "bilateral",
        "Sit with the inner legs against the pads. Bring the knees together, then return under control.",
    ),
    # Calves
    (
        "standing-calf-raise",
        "Standing Calf Raise",
        "calves",
        [],
        "machine",
        "calf_raise",
        "bilateral",
        "Stand with the balls of the feet supported and heels free to move. Raise the heels, then lower through a controlled range.",
    ),
    (
        "seated-calf-raise",
        "Seated Calf Raise",
        "calves",
        [],
        "machine",
        "calf_raise",
        "bilateral",
        "Sit with the knees secured beneath the pad and the balls of the feet supported. Raise the heels, then lower under control.",
    ),
    (
        "single-leg-bodyweight-calf-raise",
        "Single-Leg Bodyweight Calf Raise",
        "calves",
        ["core"],
        "bodyweight",
        "calf_raise",
        "unilateral",
        "Stand on one foot while using light support for balance. Raise the heel, then lower under control before changing sides.",
    ),
    # Core
    (
        "plank",
        "Plank",
        "core",
        ["shoulders"],
        "bodyweight",
        "trunk_anti_extension",
        "isometric",
        "Support the body on the forearms and toes in a straight line. Hold the trunk steady without letting the hips sag or rise.",
    ),
    (
        "side-plank",
        "Side Plank",
        "core",
        ["shoulders", "glutes"],
        "bodyweight",
        "trunk_lateral_stability",
        "isometric",
        "Support the body on one forearm and the side of one foot. Hold a straight side-on position before changing sides.",
    ),
    (
        "dead-bug",
        "Dead Bug",
        "core",
        [],
        "bodyweight",
        "trunk_anti_extension",
        "alternating",
        "Lie on the back with hips and knees bent and arms raised. Extend the opposite arm and leg while keeping the trunk steady, then alternate.",
    ),
    (
        "bird-dog",
        "Bird Dog",
        "core",
        ["glutes", "shoulders"],
        "bodyweight",
        "trunk_anti_rotation",
        "alternating",
        "Begin on hands and knees. Extend the opposite arm and leg without rotating the torso, then alternate sides.",
    ),
    (
        "cable-crunch",
        "Cable Crunch",
        "core",
        [],
        "cable",
        "trunk_flexion",
        "bilateral",
        "Kneel facing a high cable with the handle near the head. Flex the trunk to bring the ribs toward the pelvis, then return under control.",
    ),
    (
        "hanging-knee-raise",
        "Hanging Knee Raise",
        "core",
        ["forearms"],
        "pull_up_bar",
        "trunk_flexion",
        "bilateral",
        "Hang from a bar with the body steady. Raise the knees toward the torso, then lower without excessive swinging.",
    ),
    (
        "pallof-press",
        "Pallof Press",
        "core",
        ["shoulders"],
        "cable",
        "trunk_anti_rotation",
        "unilateral",
        "Stand side-on to a cable and hold the handle at the chest. Press the hands forward without letting the torso rotate, then change sides.",
    ),
    (
        "ab-wheel-rollout",
        "Ab Wheel Rollout",
        "core",
        ["shoulders", "lats"],
        "bodyweight",
        "trunk_anti_extension",
        "bilateral",
        "Kneel holding the wheel beneath the shoulders. Roll forward while keeping the trunk controlled, then pull back to the start.",
    ),
    # Full body and loaded carries
    (
        "farmers-carry",
        "Farmer's Carry",
        "full_body",
        ["forearms", "upper_back", "core", "glutes"],
        "dumbbell",
        "carry",
        "bilateral",
        "Stand tall holding a dumbbell in each hand. Walk with controlled steps while keeping the weights steady at the sides.",
    ),
    (
        "kettlebell-swing",
        "Kettlebell Swing",
        "full_body",
        ["glutes", "hamstrings", "core", "shoulders", "forearms"],
        "kettlebell",
        "hinge",
        "bilateral",
        "Hinge to guide the kettlebell between the legs. Drive the hips forward so it swings upward, then let it return into the next hinge.",
    ),
]
